name: Dispatch Release Version

on:
  release:
    types: [published]

jobs:
  release-published:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Logging
        run: |
          echo "Version=${{ github.ref_name }}"
