name: Verify PR

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    name: Verify build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint --if-present

      - name: Test
        run: |
          npm run test --if-present

      - name: Build
        run: |
          npm run build
        env:
          NODE_ENV: production
